{% set name = "pydeequ" %}
{% set version = "1.3.0" %}
{% set spark_upper_bound = "3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydeequ-{{ version }}.tar.gz
  sha256: b186b0b47b16172de0f7debddab959f4921e7012a3f048c1dc10a23bf22739f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4
  run:
    - numpy >=1.14.1
    - pandas >=0.23.0
    - python >=3.7,<4

test:
  commands:
    - export SPARK_VERSION='{{ spark_upper_bound }}'
    - python -c "import pydeequ"
    - pip check
  requires:
    - pip
    - pyspark >=2.4.7,<{{ spark_upper_bound }}

about:
  home: https://github.com/awslabs/python-deequ
  doc_url: https://pydeequ.readthedocs.io
  summary: PyDeequ - Unit Tests for Data
  license: Apache-2.0
  license_file: LICENSE
  description: |
    PyDeequ is a Python API for Deequ, a library built on top of Apache
     Spark for defining "unit tests for data", which measure data
     quality in large datasets. PyDeequ is written to support usage of
     Deequ in Python.

extra:
  recipe-maintainers:
    - thewchan
