schema_version: 1

context:
  name: pydeequ
  version: "1.7.0"
  spark_upper_bound: "3.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pydeequ-${{ version }}.tar.gz
  sha256: ce9f8f9dc2dc8fc3c585ef3facc6cddcf3bd883849ac1bb065d75d10c6dba479

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
  run:
    - numpy >=1.14.1
    - pandas >=0.23.0
    - python >=${{ python_min }}

tests:
  - requirements:
      run:
        - pip
        - pyspark >=2.4.7,<=${{ spark_upper_bound }}
        - python ${{ python_min }}.*
    script:
      - export SPARK_VERSION='${{ spark_upper_bound }}'
      - python -c "import pydeequ"
      - pip check

about:
  summary: PyDeequ - Unit Tests for Data
  license: Apache-2.0
  license_file: LICENSE
  description: |
    PyDeequ is a Python API for Deequ, a library built on top of Apache
    Spark for defining "unit tests for data", which measure data
    quality in large datasets. PyDeequ is written to support usage of
    Deequ in Python.


  homepage: https://github.com/awslabs/python-deequ
  documentation: https://pydeequ.readthedocs.io

extra:
  recipe-maintainers:
    - thewchan
